Remove ebi dev stage writer from prod
broadinstitute/monster-deploy pull request #157
Opened 2021-07-20 20:18 UTC by eparkmonster

## Why
Dev GCP service account for exporter has access to the prod bucket and need to remove that permission
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1863)

## This PR
removes 
"client_email": "ebi-staging-writer@broad-dsp-monster-hca-dev.iam.gserviceaccount.com"
from hca-prod

2021-07-21 13:38 UTC, aherbst-broad requested changes

2021-07-21 13:38 UTC, aherbst-broad commented on environments/hca-prod/terraform/buckets.tf
> +  for_each = toset([])
🔧 I think the entire `ebi_sa_bucket_iam` definition becomes a noop and should be removed

2021-07-22 12:56 UTC, aherbst-broad approved these changes

2021-07-22 13:43 UTC, quazi-broad approved these changes
lgtm

2021-07-22 13:55 UTC, merged